# Generated by Django 4.1.4 on 2023-01-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('keypair_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpc_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('extra_info', models.JSONField(editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subnet_id', models.CharField(max_length=100)),
                ('availability_zone', models.CharField(max_length=100)),
                ('extra_info', models.JSONField(null=True)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.vpc')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('security_group_id', models.CharField(max_length=200)),
                ('extra_info', models.TextField(blank=True, editable=False, null=True)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.vpc')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.operatingsystem')),
            ],
        ),
    ]
