# Generated by Django 4.1.4 on 2023-01-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancetype',
            name='short_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
