# Generated by Django 4.1.4 on 2023-01-29 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_instancetype_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingsystem',
            name='architecture',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='image_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
