# Generated by Django 4.1.4 on 2023-01-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0003_operatingsystem_architecture_operatingsystem_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatingsystem',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
