# Generated by Django 4.1.4 on 2023-01-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_alter_operatingsystem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancetype',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='instancetype',
            name='short_name',
        ),
        migrations.AddField(
            model_name='instancetype',
            name='architecture',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
