# Generated by Django 4.1.4 on 2022-12-25 04:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('modules', '0003_keypair_vpc_subnet_securitygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='EC2Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_information', models.TextField(editable=False, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('resource_requested_on', models.DateTimeField(default=datetime.datetime(2022, 12, 25, 9, 44, 1, 87316))),
                ('resource_allocation_on', models.DateTimeField(null=True)),
                ('instance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.instancetype')),
                ('key_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.keypair')),
                ('operating_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.operatingsystem')),
                ('security_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.securitygroup')),
                ('subnet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.subnet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vpc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modules.vpc')),
            ],
        ),
    ]
