# Generated by Django 4.1.4 on 2023-01-29 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2resources',
            name='resource_requested_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 29, 17, 55, 39, 104077), editable=False),
        ),
    ]
