# Generated by Django 4.1.4 on 2022-12-25 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_resources', '0002_alter_ec2resources_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2resources',
            name='resource_allocation_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ec2resources',
            name='resource_requested_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 25, 9, 45, 57, 152537), editable=False),
        ),
    ]
