# Generated by Django 4.1.4 on 2023-01-30 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_resources', '0003_alter_ec2resources_resource_requested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2resources',
            name='resource_requested_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 17, 52, 57, 543407), editable=False),
        ),
    ]
