# Generated by Django 4.1.4 on 2023-01-30 12:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_resources', '0004_alter_ec2resources_resource_requested_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ec2resources',
            name='resource_requested_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 17, 58, 11, 752082), editable=False),
        ),
    ]
